name: Tox CI

on:
  - pull_request
  - workflow_dispatch

env:
  PY_COLORS: "1"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.7", "pypy3.8", "pypy3.9"]
        fail-fast: [false]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions python-can
    - name: Test with tox
      run: tox
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.coveralls_github_token }}
        flag-name: Unittests-${{ matrix.os }}-${{ matrix.python-version }}
        parallel: true
        path-to-lcov: ./coverage.lcov

  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.coveralls_github_token }}
        parallel-finished: true
